# Generated by Django 5.0.5 on 2024-05-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('user_last_name', models.CharField(max_length=200, verbose_name='Фамилия пользователя')),
                ('company_name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_last_name', models.CharField(max_length=200, verbose_name='Фамилия клиента')),
                ('client_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_client.users', verbose_name='Пользуется услугами компании')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
